api_platform:
    title: Movie API
    version: 1.0.0
    show_webby: false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_items_per_page: 10
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header